# Generated by Django 4.1.5 on 2023-01-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifiers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
