# Generated by Django 4.1.5 on 2023-01-15 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantdb', '0002_alter_modifiers_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Modifiers',
            new_name='Modifier',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=10000)),
                ('price', models.DecimalField(decimal_places=10, max_digits=60)),
                ('modifiers', models.ManyToManyField(to='restaurantdb.modifier')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantdb.section')),
            ],
        ),
    ]
