# Generated by Django 4.1.5 on 2023-01-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantdb', '0003_section_rename_modifiers_modifier_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='modifiers',
            field=models.ManyToManyField(blank=True, to='restaurantdb.modifier'),
        ),
    ]
