# Generated by Django 4.1.5 on 2023-01-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantdb', '0004_alter_item_modifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurantdb.section'),
        ),
    ]
