# Generated by Django 4.1.5 on 2023-01-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantdb', '0006_alter_item_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='modifiers',
            field=models.ManyToManyField(blank=True, related_name='item', to='restaurantdb.modifier'),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
