# Generated by Django 4.1.5 on 2023-01-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantdb', '0007_alter_item_id_alter_item_modifiers_alter_modifier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='modifiers',
            field=models.ManyToManyField(blank=True, null=True, related_name='item', to='restaurantdb.modifier'),
        ),
    ]
