# Generated by Django 4.1.5 on 2023-01-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantdb', '0009_alter_item_name_alter_modifier_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='modifiers',
            field=models.ManyToManyField(blank=True, related_name='item', to='restaurantdb.modifier'),
        ),
    ]
